// <auto-generated />
using System;
using CarDealershipsSystem.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarDealershipsSystem.DAL.Migrations
{
    [DbContext(typeof(CarDealershipsDbContext))]
    [Migration("20221119112309_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarDealershipsSystem.DAL.Repositories.Branch", b =>
                {
                    b.Property<int>("IdBranch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_BRANCH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBranch"));

                    b.Property<string>("BranchAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("BRANCH_ADDRESS");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("BRANCH_NAME");

                    b.Property<string>("HeadMiddlename")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("HEAD_MIDDLENAME");

                    b.Property<string>("HeadName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("HEAD_NAME");

                    b.Property<long>("HeadPassData")
                        .HasColumnType("bigint")
                        .HasColumnName("HEAD_PASS_DATA");

                    b.Property<string>("HeadPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("HEAD_PHONE_NUMBER");

                    b.Property<string>("HeadSurname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("HEAD_SURNAME");

                    b.HasKey("IdBranch")
                        .HasName("PK__BRANCH__261C45A4714DCBF7");

                    b.HasIndex(new[] { "HeadPassData" }, "UQ__BRANCH__1DEAC273B604FA0C")
                        .IsUnique();

                    b.HasIndex(new[] { "HeadPhoneNumber" }, "UQ__BRANCH__5F3A4AF4994A30AB")
                        .IsUnique();

                    b.ToTable("BRANCH", (string)null);
                });

            modelBuilder.Entity("CarDealershipsSystem.DAL.Repositories.Buyer", b =>
                {
                    b.Property<long>("BuyerPassData")
                        .HasColumnType("bigint")
                        .HasColumnName("BUYER_PASS_DATA");

                    b.Property<string>("BuyerMiddlename")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("BUYER_MIDDLENAME");

                    b.Property<string>("BuyerName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("BUYER_NAME");

                    b.Property<string>("BuyerPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("BUYER_PHONE_NUMBER");

                    b.Property<string>("BuyerSurname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("BUYER_SURNAME");

                    b.HasKey("BuyerPassData")
                        .HasName("PK__BUYER__ABE081A1CB4B8249");

                    b.HasIndex(new[] { "BuyerPhoneNumber" }, "UQ__BUYER__7FDA2467C6A8FD4A")
                        .IsUnique();

                    b.ToTable("BUYER", (string)null);
                });

            modelBuilder.Entity("CarDealershipsSystem.DAL.Repositories.Car", b =>
                {
                    b.Property<int>("IdCar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_CAR");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCar"));

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("BODY_TYPE");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("BRAND");

                    b.Property<int>("IdBranch")
                        .HasColumnType("int")
                        .HasColumnName("ID_BRANCH");

                    b.Property<int>("IdOrder")
                        .HasColumnType("int")
                        .HasColumnName("ID_ORDER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("MODEL");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("QUANTITY");

                    b.HasKey("IdCar")
                        .HasName("PK__CAR__2BF8FA1E804D4674");

                    b.HasIndex("IdBranch");

                    b.HasIndex("IdOrder");

                    b.ToTable("CAR", (string)null);
                });

            modelBuilder.Entity("CarDealershipsSystem.DAL.Repositories.CarExemplar", b =>
                {
                    b.Property<string>("VinNumber")
                        .HasMaxLength(17)
                        .IsUnicode(false)
                        .HasColumnType("varchar(17)")
                        .HasColumnName("VIN_NUMBER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("COLOR");

                    b.Property<int>("HorsePower")
                        .HasColumnType("int")
                        .HasColumnName("HORSE_POWER");

                    b.Property<int>("IdCar")
                        .HasColumnType("int")
                        .HasColumnName("ID_CAR");

                    b.Property<decimal>("Price")
                        .HasColumnType("money")
                        .HasColumnName("PRICE");

                    b.Property<DateTime>("YearOfAssembly")
                        .HasColumnType("date")
                        .HasColumnName("YEAR_OF_ASSEMBLY");

                    b.HasKey("VinNumber")
                        .HasName("PK__CAR_EXEM__B372A1A30439A375");

                    b.HasIndex("IdCar");

                    b.ToTable("CAR_EXEMPLAR", (string)null);
                });

            modelBuilder.Entity("CarDealershipsSystem.DAL.Repositories.CarOrder", b =>
                {
                    b.Property<int>("IdOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_ORDER");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrder"));

                    b.Property<long>("BuyerPassData")
                        .HasColumnType("bigint")
                        .HasColumnName("BUYER_PASS_DATA");

                    b.Property<DateTime>("ContractDate")
                        .HasColumnType("date")
                        .HasColumnName("CONTRACT_DATE");

                    b.Property<long>("MngrPassData")
                        .HasColumnType("bigint")
                        .HasColumnName("MNGR_PASS_DATA");

                    b.Property<decimal>("OrderAmount")
                        .HasColumnType("money")
                        .HasColumnName("ORDER_AMOUNT");

                    b.HasKey("IdOrder")
                        .HasName("PK__CAR_ORDE__D23A85655E8E6594");

                    b.HasIndex("BuyerPassData");

                    b.HasIndex("MngrPassData");

                    b.ToTable("CAR_ORDER", (string)null);
                });

            modelBuilder.Entity("CarDealershipsSystem.DAL.Repositories.Manager", b =>
                {
                    b.Property<long>("MngrPassData")
                        .HasColumnType("bigint")
                        .HasColumnName("MNGR_PASS_DATA");

                    b.Property<int>("IdBranch")
                        .HasColumnType("int")
                        .HasColumnName("ID_BRANCH");

                    b.Property<string>("MngrMiddlename")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("MNGR_MIDDLENAME");

                    b.Property<string>("MngrName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("MNGR_NAME");

                    b.Property<DateTime>("MngrPayDate")
                        .HasColumnType("date")
                        .HasColumnName("MNGR_PAY_DATE");

                    b.Property<string>("MngrPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MNGR_PHONE_NUMBER");

                    b.Property<decimal?>("MngrPrize")
                        .HasColumnType("money")
                        .HasColumnName("MNGR_PRIZE");

                    b.Property<decimal>("MngrSalary")
                        .HasColumnType("money")
                        .HasColumnName("MNGR_SALARY");

                    b.Property<string>("MngrSurname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("MNGR_SURNAME");

                    b.HasKey("MngrPassData")
                        .HasName("PK__MANAGER__91EE6294FA89A267");

                    b.HasIndex("IdBranch");

                    b.HasIndex(new[] { "MngrPhoneNumber" }, "UQ__MANAGER__AB6758BFC77CA6E2")
                        .IsUnique();

                    b.ToTable("MANAGER", (string)null);
                });

            modelBuilder.Entity("CarDealershipsSystem.DAL.Repositories.Car", b =>
                {
                    b.HasOne("CarDealershipsSystem.DAL.Repositories.Branch", "IdBranchNavigation")
                        .WithMany("Cars")
                        .HasForeignKey("IdBranch")
                        .IsRequired()
                        .HasConstraintName("FK__CAR__ID_BRANCH__45F365D3");

                    b.HasOne("CarDealershipsSystem.DAL.Repositories.CarOrder", "IdOrderNavigation")
                        .WithMany("Cars")
                        .HasForeignKey("IdOrder")
                        .IsRequired()
                        .HasConstraintName("FK__CAR__ID_ORDER__47DBAE45");

                    b.Navigation("IdBranchNavigation");

                    b.Navigation("IdOrderNavigation");
                });

            modelBuilder.Entity("CarDealershipsSystem.DAL.Repositories.CarExemplar", b =>
                {
                    b.HasOne("CarDealershipsSystem.DAL.Repositories.Car", "IdCarNavigation")
                        .WithMany("CarExemplars")
                        .HasForeignKey("IdCar")
                        .IsRequired()
                        .HasConstraintName("FK__CAR_EXEMP__ID_CA__5070F446");

                    b.Navigation("IdCarNavigation");
                });

            modelBuilder.Entity("CarDealershipsSystem.DAL.Repositories.CarOrder", b =>
                {
                    b.HasOne("CarDealershipsSystem.DAL.Repositories.Buyer", "BuyerPassDataNavigation")
                        .WithMany("CarOrders")
                        .HasForeignKey("BuyerPassData")
                        .IsRequired()
                        .HasConstraintName("FK__CAR_ORDER__BUYER__412EB0B6");

                    b.HasOne("CarDealershipsSystem.DAL.Repositories.Manager", "MngrPassDataNavigation")
                        .WithMany("CarOrders")
                        .HasForeignKey("MngrPassData")
                        .IsRequired()
                        .HasConstraintName("FK__CAR_ORDER__MNGR___403A8C7D");

                    b.Navigation("BuyerPassDataNavigation");

                    b.Navigation("MngrPassDataNavigation");
                });

            modelBuilder.Entity("CarDealershipsSystem.DAL.Repositories.Manager", b =>
                {
                    b.HasOne("CarDealershipsSystem.DAL.Repositories.Branch", "IdBranchNavigation")
                        .WithMany("Managers")
                        .HasForeignKey("IdBranch")
                        .IsRequired()
                        .HasConstraintName("FK__MANAGER__ID_BRAN__36B12243");

                    b.Navigation("IdBranchNavigation");
                });

            modelBuilder.Entity("CarDealershipsSystem.DAL.Repositories.Branch", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("Managers");
                });

            modelBuilder.Entity("CarDealershipsSystem.DAL.Repositories.Buyer", b =>
                {
                    b.Navigation("CarOrders");
                });

            modelBuilder.Entity("CarDealershipsSystem.DAL.Repositories.Car", b =>
                {
                    b.Navigation("CarExemplars");
                });

            modelBuilder.Entity("CarDealershipsSystem.DAL.Repositories.CarOrder", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("CarDealershipsSystem.DAL.Repositories.Manager", b =>
                {
                    b.Navigation("CarOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
